### ISSUE TITLE
TypeError: normal() received an invalid combination of arguments - got (std=float, means=Tensor, )

### ISSUE THREAD

**Issue by dendisuhubdy** [leftthomas/SEGAN#13]
```$~/code/SEGAN$ python3 main.py --batch_size 128 --num_epochs 300
/home/machine/.local/lib/python3.6/site-packages/numba/errors.py:137: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
loading data...
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    discriminator = Discriminator()
  File "/home/machine/code/SEGAN/model.py", line 228, in __init__
    self.vbn1 = VirtualBatchNorm1d(32)
  File "/home/machine/code/SEGAN/model.py", line 21, in __init__
    self.gamma = Parameter(torch.normal(means=torch.ones(1, num_features, 1), std=0.02))
TypeError: normal() received an invalid combination of arguments - got (std=float, means=Tensor, ), but expected one of:
 * (Tensor mean, Tensor std, torch.Generator generator, Tensor out)
 * (Tensor mean, float std, torch.Generator generator, Tensor out)
 * (float mean, Tensor std, torch.Generator generator, Tensor out)
 * (float mean, float std, tuple of ints size, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)```

**Comment by leftthomas** [comment]
@dendisuhubdy have fixed

**Comment by dendisuhubdy** [comment]
@leftthomas which commit?

**Comment by dendisuhubdy** [comment]
@leftthomas oh this one 716f3e6 thanks man!
